verbose = false

[sumo]
port = 10000
sumocfg-path = "katrinebjerg-lamp/katrinebjerg-lamp.sumocfg"
osm-path = "katrinebjerg-lamp/katrinebjerg-lamp.osm"
simulation-steps = 1000000
deallocate-inactive-cars-every = 10000   # in simulation steps
start-datetime = 2023-12-14T22:00:00Z    # ISO 8601
delay-per-simulated-second = 0.1         # in seconds

[sumo.spawn]
enabled = true
gui = false

[sumo.streetlamps]
distance-threshold = 50 # in meters

[sumo.publisher]
port = 12000

[sumo.publisher.topics.cars]
enabled = true
name = "cars"
publish-rate = 1 # in Hz

[sumo.publisher.topics.streetlamps]
enabled = true
name = "streetlamps"
publish-rate = 0.5   # in Hz


[server.streetlamps]
port = 12001
db-path = "streetlamps.sqlite3"
