verbose = false
port = 12000

[sumo]
port = 10000
sumocfg-path = "horsens/horsens.sumocfg"
osm-path = "horsens/horsens.osm"
simulation-steps = 100000
deallocate-inactive-cars-every = 10000    # in simulation steps
start-datetime = 1979-05-27T07:32:00Z
delay-per-simulated-second = 0.1 # in seconds

[sumo.spawn]
enabled = true
gui = false

[sumo.streetlamps]
distance-threshold = 50 # in meters

[topics.cars]
enabled = true
name = "cars"
publish-rate = 1 # in Hz

[topics.streetlamps]
enabled = true
name = "streetlamps"
publish-rate = 0.5    # in Hz


[server.streetlamps]
port = 12001
