verbose = false
port = 12000

[sumo]
port = 10000
sumocfg-path = "horsens/horsens.sumocfg"
osm-path = "horsens/horsens.osm"
simulation-steps = 10000
deallocate-inactive-cars-every = 1000    # in simulation steps

[sumo.spawn]
enabled = true
gui = false

[sumo.streetlamps]
distance-threshold = 50 # in meters

[topics.cars]
enabled = true
name = "cars"
publish-rate = 5 # in Hz

[topics.streetlamps]
enabled = true
name = "streetlamps"
publish-rate = 10    # in Hz
