verbose = true
port = 5555
publish-rate = 10 # in Hz

[sumo]
port = 10000
sumocfg-path = "katrinebjerg-lamp/katrinebjerg-lamp.sumocfg"
osm-path = "katrinebjerg-lamp/katrinebjerg-lamp.osm"
simulation-steps = 10000
deallocate-inactive-cars-every = 1000 # in simulation steps

[sumo.spawn]
enabled = true
gui = false

[sumo.streetlamps]
distance-threshold = 50 # in meters

[topics.cars]
name = "cars"
