[project]
name = "sumo-networks"
version = "0.1.0"
description = "Add a short description here"
authors = ["kpbaks <kristoffer.pbs@tuta.io>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.12.0.*"
websockets = "12.0.*"
cbor2 = "5.5.1.*"
pyzmq = "25.1.1.*"
rich = "13.6.0.*"
loguru = "0.7.2.*"
result = "0.15.0.*"
faker = "20.1.0.*"
